### ISSUE TITLE
using /deploy directory leads to "serious trouble in main loop"

### ISSUE THREAD

**Issue by mukil** [digitalmemex/distribution#4]
I suddenly had the issue of the following stacktrace

<pre>
2015-03-19 14:22:03,275 | ERROR | -SNAPSHOT/deploy | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.4.2 | In main loop, we have serious trouble
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)[:1.7.0_75]
    at java.util.ArrayList.get(ArrayList.java:411)[:1.7.0_75]
    at org.apache.felix.framework.BundleImpl.adapt(BundleImpl.java:1082)[org.apache.felix.framework-4.4.1.jar:]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.isFragment(DirectoryWatcher.java:665)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1236)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1207)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:504)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310)[6:org.apache.felix.fileinstall:3.4.2]
2015-03-19 14:22:03,276 | ERROR | -SNAPSHOT/deploy | fileinstall                      | 6 - org.apache.felix.fileinstall - 3.4.2 | In main loop, we have serious trouble
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    at java.util.ArrayList.rangeCheck(ArrayList.java:635)[:1.7.0_75]
    at java.util.ArrayList.get(ArrayList.java:411)[:1.7.0_75]
    at org.apache.felix.framework.BundleImpl.adapt(BundleImpl.java:1082)[org.apache.felix.framework-4.4.1.jar:]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.isFragment(DirectoryWatcher.java:665)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1236)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1217)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.startAllBundles(DirectoryWatcher.java:1207)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:504)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:358)[6:org.apache.felix.fileinstall:3.4.2]
    at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:310)[6:org.apache.felix.fileinstall:3.4.2]
</pre>

Leading to the point that i can not start up the system anymore. No karaf and no dm4 plugins seems to boot correctly, all i get after running `./bin/start` is the following message in te `karaf.log`. 

<pre>
Mrz 20, 2015 7:20:43 PM org.apache.karaf.main.SimpleFileLock lock
INFORMATION: locking
Mrz 20, 2015 7:20:44 PM org.apache.karaf.main.SimpleFileLock lock
INFORMATION: locking
Mrz 20, 2015 7:20:45 PM org.apache.karaf.main.SimpleFileLock lock
INFORMATION: locking
Mrz 20, 2015 7:20:46 PM org.apache.karaf.main.SimpleFileLock lock
INFORMATION: locking
Mrz 20, 2015 7:20:47 PM org.apache.karaf.main.SimpleFileLock lock
INFORMATION: locking
</pre>

I cant bring up my existing dmx-installation anymore.

**Comment by mukil** [comment]
BTW: The hot-deployment through copying bundles into the `/deploy`is a very nice and distinct DMX feature, mostly because this seems to (potentially) enable hot-deployment of bundles for plugin-developers without building the platform from source.

**Comment by mukil** [comment]
After some rounds of using the `start` and `stop` command the system finally got up again .. but i think this behaviour could lead to annoying trouble in some cases. I will try to investigate if this is also an issue if i just use the `/system` folder to deploy my bundles and how one can reproduce this starting from a fresh dmx-installation.
